name: DevOps Workflow


on:
  push:
    branches:
      - main


jobs:  
   build:
      runs-on: ubuntu-latest


      steps:

      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Mostrar Menssagem
        run: echo "Olá, Mundo DevOps!"

      - name: Checkout de Códigos
        uses: actions/checkout@v4

      - name: Build Aplicacao
        run: echo "Buildando a Aplicação"


   dev:
      runs-on: ubuntu-latest
      needs: build

      steps:
       - name: Fase de Desenvolvimento
         run: echo "Deploy no ambiente de desenvolvimento"


   qa:     
      runs-on: ubuntu-latest
      needs: build

      steps:
       - name: Fase de Teste e Qualidade 
         run: echo "Executar os teste de Qualidade"


   homologacao: 
      needs: 
        - qa
        - dev    
      runs-on: ubuntu-latest
      

      steps:
       - name: Deploy Homol 
         run: echo "Executando Deploy no ambiente de  Homologação"


   producao:
     needs: homologacao
     runs-on: ubuntu-latest


     steps:
      - name: Deploy Prod
        run: echo "Executando Deploy em PRD"
    
